# Generated by Django 3.2.25 on 2024-06-11 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('idGrado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreGrado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('idSeccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSeccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GradoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grado_secciones', to='accounts.grado')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grado_secciones', to='accounts.seccion')),
            ],
            options={
                'unique_together': {('grado', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreAlumno', models.TextField(max_length=100)),
                ('apellidoAlumno', models.TextField(max_length=100)),
                ('edadAlumno', models.IntegerField()),
                ('numeroTelefonoAlumno', models.CharField(max_length=8)),
                ('fechaRegistroAlumno', models.DateField(auto_now_add=True)),
                ('nombreResponsable', models.TextField(max_length=100)),
                ('apellidoResposable', models.TextField(max_length=100)),
                ('numeroTelefonoResposable', models.CharField(max_length=8)),
                ('duiResponsable', models.CharField(max_length=9, unique=True)),
                ('direccionResponsable', models.TextField(max_length=100)),
                ('edadResponsable', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('dui', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nombreDocente', models.TextField(max_length=100)),
                ('apellidoDocente', models.TextField(max_length=100)),
                ('generoDocente', models.CharField(max_length=1)),
                ('direccionDocente', models.TextField(max_length=100)),
                ('correoDocente', models.EmailField(max_length=254, unique=True)),
                ('fechaRegistroDocente', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='accounts.docente')),
                ('grado_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='accounts.gradoseccion')),
            ],
        ),
    ]
