# Generated by Django 3.2.25 on 2024-10-17 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadacademica',
            name='id_alumno',
        ),
        migrations.RemoveField(
            model_name='actividadacademica',
            name='nota',
        ),
        migrations.AlterField(
            model_name='docentemateriagrado',
            name='dui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.docente'),
        ),
        migrations.CreateModel(
            name='NotaActividad',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nota', models.FloatField()),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.actividadacademica')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.estudiante')),
            ],
        ),
    ]
