# Generated by Django 3.2.25 on 2024-10-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistio',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente')], max_length=1),
        ),
    ]
