# Generated by Django 3.2.25 on 2024-06-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='edadDocente',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='telefonoDocente',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidoAlumno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellidoResposable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccionResponsable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombreAlumno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombreResponsable',
            field=models.CharField(max_length=100),
        ),
    ]
