# Generated by Django 3.2.25 on 2024-10-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentemateriagrado',
            name='dia',
            field=models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado'), ('Sunday', 'Domingo')], default='Monday', max_length=9),
        ),
        migrations.AddField(
            model_name='docentemateriagrado',
            name='hora_fin',
            field=models.TimeField(default='1:00'),
        ),
        migrations.AddField(
            model_name='docentemateriagrado',
            name='hora_inicio',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddConstraint(
            model_name='docentemateriagrado',
            constraint=models.UniqueConstraint(fields=('dui', 'dia', 'hora_inicio', 'hora_fin'), name='unique_horario_docente'),
        ),
    ]
