# Generated by Django 3.2.25 on 2024-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

   # dependencies = [
        #('accounts', '0002_auto_20240614_1119'),
    #]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='generoDocente',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
