# Generated by Django 3.2.25 on 2024-10-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241016_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadacademica',
            name='id_tipoactividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.tipoactividad'),
        ),
    ]
