# Generated by Django 3.2.25 on 2024-06-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240614_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='apellidoDocente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docente',
            name='direccionDocente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombreDocente',
            field=models.CharField(max_length=100),
        ),
    ]
