# Generated by Django 3.2.25 on 2024-10-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241006_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=9)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='docentemateriagrado',
            name='unique_horario_docente',
        ),
        migrations.RemoveField(
            model_name='docentemateriagrado',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='docentemateriagrado',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='docentemateriagrado',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='horarioclase',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.docente'),
        ),
        migrations.AddField(
            model_name='horarioclase',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioclase',
            unique_together={('docente', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
    ]
