# Generated by Django 3.2.25 on 2024-06-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    #dependencies = [
       # ('accounts', '0003_estudiante_generodocente'),
    #]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='generoDocente',
            new_name='generoAlunmo',
        ),
    ]
